---
hpc:
        bcftools_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/bcftools-1.3.1/bcftools"
        blast_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/ncbi-blast-2.6.0+/bin"
        bowtie2_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/bowtie2-2.1.0/bowtie2"
        bowtie2build_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/bowtie2-2.1.0/bowtie2-build"
        cdhit_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/cd-hit-v4.6.1-2012-08-27/cd-hit-est"
        cdhitdup_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/cd-hit-v4.6.1-2012-08-27/cd-hit-auxtools/cd-hit-dup"
        cutadapt_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/cutadapt-1.8.3/bin/cutadapt"
        fastqc_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/FastQC/fastqc"
        gb_database_EXEC: "/ifs/scratch/msph/cii/bl2493/Databases/Genbank/May_2017/"
        refseq_database_EXEC: "/ifs/scratch/msph/cii/bl2493/Databases/Genbank/May_2017/refseq/"
        java_EXEC: "/nfs/apps/java/1.8.0_91/bin/java"
        megahit_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/megahit"
        mira_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/mira_4.0_linux-gnu_x86_64_static/bin"
        perl_EXEC: "perl"
        prinseq_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/prinseq-lite-0.20.3/prinseq-lite.pl"
        prinseq_graph_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/prinseq-lite-0.20.3/prinseq-graphs.pl"
        qsub_EXEC: "/opt/gridengine/hpc/bin/lx-amd64/qsub"
        sambamba_EXEC: "NA"
        samtools_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/samtools-1.3.1/samtools" 
        soap_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/SOAPdenovo2"
        vcfutils_EXEC: "/ifs/scratch/msph/cii/bl2493/Software/bcftools-1.3.1/vcfutils.pl"
        metaphlandir_EXEC: "/ifs/home/msph/cii/cg2984/software/metaphlan2"
        metaphlan_EXEC: "/ifs/home/msph/cii/cg2984/software/metaphlan2/metaphlan2.py"
cii:
        bcftools_EXEC: "/share/data/software/bcftools-1.3.1/bcftools"
        bedtools_EXEC: "/share/data/software/bedtools2/bin/bedtools"
        blast_EXEC: "/share/data/software/ncbi-blast-2.6.0+/bin"
        bowtie2_EXEC: "/share/data/software/bowtie2-2.2.9/bowtie2"
        bowtie2build_EXEC: "/share/data/software/bowtie2-2.2.9/bowtie2-build"
        cdhit_EXEC: "/share/data/software/cdhit/cd-hit-est"
        cdhitdup_EXEC: "/share/data/software/cdhit/cd-hit-auxtools/cd-hit-dup"     
        cutadapt_EXEC: "/share/data/software/bin/cutadapt"
        emboss_EXEC: "/share/data/software/bin/"
        fastqc_EXEC: "/share/data/software/FastQC/fastqc"
        flash_EXEC: "/share/data/software/FLASH-1.2.11/flash"
        gb_database_EXEC: "/share/data/Databases/GenBank/May_2017/"
        refseq_database_EXEC: "/share/data/Databases/GenBank/May_2017/refseq/"
        genemarkS_EXEC: "/share/data/software/genemark_suite_linux_64/gmsuite/gmsn.pl"
        java_EXEC: "/share/data/software/jre1.8.0_101/bin/java"
        megahit_EXEC: "/share/data/software/megahit"
        mira_EXEC: "/share/data/software/mira_4.0_linux-gnu_x86_64_static/bin"
        needle_EXEC: "/share/data/software/bin/needle"
        perl_EXEC: "/share/data/software/perlbrew/perls/perl-5.25.4/bin/perl"
        prinseq_EXEC: "/share/data/software/prinseq-lite-0.20.3/prinseq-lite.pl"
        prinseq_graph_EXEC: "/share/data/software/prinseq-lite-0.20.3/prinseq-graphs.pl"
        qsub_EXEC: "/opt/ogs/bin/linux-x64/qsub"
        sambamba_EXEC: "/share/data/software/bin/sambamba_v0.6.6"
        samtools_EXEC: "/share/data/software/samtools-1.3.1/samtools"
        soap_EXEC: "/share/data/software/SOAPdenovo2"
        tagcleaner_EXEC: "/share/data/software/tagcleaner-standalone-0.16/tagcleaner.pl"
        vcfutils_EXEC: "/share/data/software/bcftools-1.3.1/vcfutils.pl"
        metaphlandir_EXEC: "/share/home/cheng/software/metaphlan2"
        metaphlan_EXEC: "/share/home/cheng/software/metaphlan2/metaphlan2.py"
        python_EXEC: "/share/data/software/miniconda2/bin/python"
        kraken2_EXEC: "/share/data/software/kraken2/kraken2/kraken2"
ps-Super-Server:
        fastqc_EXEC: "~/softwares/fastqc/FastQC/fastqc"
	cutadapt_EXEC: "/home/cheng/softwares/miniconda2/bin/cutadapt"
	prinseq_EXEC: "/home/cheng/softwares/miniconda2/bin/prinseq-lite.pl"
        prinseq_graph_EXEC: "/home/cheng/softwares/miniconda2/bin/prinseq-graphs.pl"

other:



